name: APK

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-platform: 'platforms;android-30'
        ndk-version: '21.4.7075529'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        
    - name: Create Directories
      run: mkdir ./bin/debug
     
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build APK
      run: python build.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: t-engine debug APK
        path: ./bin/debug
